create table public.observations (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  docente text not null,
  grupo text default '',
  asignatura text default '',
  fecha date not null,
  campo_formativo text not null,
  ejes jsonb not null default '[]'::jsonb,
  elapsed_seconds integer not null default 0,
  bitacora jsonb not null default '[]'::jsonb,
  ratings jsonb not null default '{}'::jsonb,
  feedback jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.observations enable row level security;
create policy "Users can view their own observations" on public.observations for select using (auth.uid() = user_id);
create policy "Users can insert their own observations" on public.observations for insert with check (auth.uid() = user_id);
create policy "Users can update their own observations" on public.observations for update using (auth.uid() = user_id);
create policy "Users can delete their own observations" on public.observations for delete using (auth.uid() = user_id);
